version: '3.12'

services:
  backend:
    build:
      context: ./dashboard-backend
    ports:
      - "8000:8000"
    volumes:
      - ./dashboard-backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./dashboard-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard-frontend:/app
    env_file:
      - .env
    command: ["npm", "run", "dev"]
